[package]
name = "leafline"
version = "0.0.16-prealpha"
authors = ["Zack M. Davis <code@zackmdavis.net>"]

[lib]
path = "src/lib.rs"
crate-type = ["dylib"]

[[bin]]
name = "leafline"
path = "src/main.rs"

[dependencies]
ansi_term = "0.6"
argparse = "0.2"
clippy = { git = "https://github.com/Manishearth/rust-clippy" }
itertools = "0.4"
libc = "0.2"
log = "0.3"
lru-cache = "0.0.5"
rustc-serialize = "0.3"
time = "0.1"
twox-hash = "0.1.1"

[profile.dev]
opt-level = 3

[profile.release]
lto = true
