[package]
name = "leafline"
version = "0.0.11"
authors = ["Zack M. Davis <code@zackmdavis.net>"]

[dependencies]
ansi_term = "0.6.3"
argparse = "0.2.0"
clippy = "*"
itertools = "0.3.25"
rustc-serialize = "0.3.16"
time = "0.1.32"
