---
- hosts: all
  tasks:
    - name: firewall allow 2882
      sudo: yes
      ufw: >
        rule=allow
        proto=tcp
        port=2882
      tags:
        - firewall

    - name: give www-data a shell
      sudo: yes
      user: >
        name=www-data
        shell=/bin/bash

    - name: install Java
      sudo: yes
      apt: name=default-jre-headless state=present
      tags:
        - jvm

    - name: make /srv/leafline directory
      sudo: yes
      file: path=/srv/leafline state=directory owner=www-data group=www-data
      tags:
        - application

    # let's suppose that the binary and jar have been copied into the
    # provisioning/ directory of our local repository

    - name: copy Leafline binary
      sudo: yes
      copy: >
        src=leafline
        dest=/srv/leafline/leafline
        mode=755
        force=yes
        owner=www-data
        group=www-data
      tags:
        - application

    - name: copy Leafline Web jar
      sudo: yes
      copy: >
        src=leafline-web-client.jar
        dest=/srv/leafline/leafline-web-client.jar
        mode=755
        force=yes
        owner=www-data
        group=www-data
      tags:
        - application

    - name: install Upstart job
      sudo: yes
      template: >
        src=leafline.conf.j2
        dest=/etc/init/leafline.conf
      tags:
        - upstart
        - application

    - name: run Leafline service
      sudo: yes
      service: >
        name=leafline
        state=restarted
        enabled=yes
      tags:
        - upstart
        - application
